name: Build for armel (static)

on:
  push:
  pull_request:
  schedule:
    # Weekly build (on saturday)
    - cron: '0 0 * * 6'

jobs:
  build-armel:
    runs-on: ubicloud-standard-2-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    # - name: Update apt indexes
    #   run: sudo apt-get update
    # - name: Install various apt dependencies
    #   run: sudo apt-get install build-essential cmake meson ninja-build nlohmann-json3-dev pkg-config libssl-dev libsdl2-dev
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Build armel image
      run: cd scripts/build-targets && make armel
    - name: Configure Meson
      run: scripts/build-targets/run armel sh -c 'LDFLAGS="-static -latomic" linux32 meson setup build-armel --prefer-static -Dbuildtype=release -Dlvgl-driver=fbdev'
    - name: Build
      run: scripts/build-targets/run armel sh -c 'linux32 meson compile -C build-armel'
    # FIXME: put something useful (git hash?) in artifact name. We also want this in other workflows.
    - uses: actions/upload-artifact@v4
      with:
        name: armel-build
        path: ${{github.workspace}}/build-armel
